# .bashrc
# this was transferred from fedora to fedora to fedora idk the %90 stuff here TT they were autogenerated

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

for file in ~/.bash_{aliases,exports,functions}; do
  [ -r "$file" ] && source "$file"
done

export PATH


# path stuff
export PATH=/home/selim/standalone/jdk-22.0.2/bin:$PATH
export PATH=/home/selim/.local/share/JetBrains/Toolbox/scripts:$PATH
export PATH=/home/selim/standalone/flutter_sdk/flutter/bin:$PATH
export PATH=/home/selim/Android/Sdk/cmdline-tools/latest/bin:$PATH

export EDITOR=/usr/bin/code
export DEVKITPPC=/opt/devkitpro/devkitPPC
export NVM_DIR="$HOME/.nvm"
. "$HOME/.cargo/env"

RESET="\[\017\]"
NORMAL="\[\033[0m\]"
RED="\[\033[31;1m\]"
ORANGE="\[\033[38;5;214m\]"
YELLOW="\[\033[33;1m\]"
GREEN="\[\033[32;1m\]"
BLUE="\[\033[34;1m\]"
CYAN="\[\033[36;1m\]"
MAGENTA="\[\033[35;1m\]"
PURPLE="\033[38;5;129m"
WHITE="\[\033[37;1m\]"
SMILEY="${GREEN}:)${NORMAL}"
FROWNY="${RED}:(${NORMAL}"
SELECT="if [ \$? = 0 ]; then echo \"${SMILEY}\"; else echo \"${FROWNY}\"; fi"

PS1="${RESET}${YELLOW}\u${NORMAL}@${YELLOW}\h${NORMAL} \`${SELECT}\` ${WHITE} ${YELLOW}\w${NORMAL} >${NORMAL} "

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export GPG_TTY=$(tty)

# EOF .bashrc
