# .bashrc
# this was transferred from fedora to fedora to fedora idk the %90 stuff here TT they were autogenerated

for file in ~/.bash_{aliases,exports,functions}; do
  [ -r "$file" ] && source "$file"
done

export PATH

RESET="\[\017\]"
NORMAL="\[\033[0m\]"
RED="\[\033[31;1m\]"
ORANGE="\[\033[38;5;214m\]"
YELLOW="\[\033[33;1m\]"
GREEN="\[\033[32;1m\]"
BLUE="\[\033[34;1m\]"
CYAN="\[\033[36;1m\]"
MAGENTA="\[\033[35;1m\]"
PURPLE="\033[38;5;129m"
WHITE="\[\033[37;1m\]"
HAPPY="${GREEN}:)${NORMAL}"
SAD="${RED}:(${NORMAL}"
SELECT="if [ \$? = 0 ]; then echo \"${HAPPY}\"; else echo \"${SAD}\"; fi"

PS1="${RESET}${YELLOW}\u${NORMAL}@${YELLOW}\h${NORMAL} \`${SELECT}\` ${WHITE} ${YELLOW}\w${NORMAL} >${NORMAL} "

export GPG_TTY=$(tty)

# EOF .bashrc
